title: Snehal Shirgure
email: snehalshirgure@gmail.com
#  Personal website of Snehal Shirgure
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed